# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args: ['--branch', 'main']
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        args: ["--exclude", "setup.py,tests"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        exclude: ^tests/,^examples/
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2
    hooks:
    -   id: pylint
-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell --ignore-words ignore-spelling-words.txt pytextrank/*.py *.md docs/*.md
        language: python
        types: [text]
